---
note_type: note
tags:
  - web_development
  - javascript
  - promises
mn: "[[12.5 Javascript]]"
kt: theorical
checked: false
---
[[12.5 Javascript|JavaScript]]

## Promise constructor
Once the constructor is executed, a new promise object is created in memory. It can be bind to a variable, return right away or return inside a function.

```js
let promise = new Promise(function(resolve, reject) {
  // executor (the producing code, "singer")
});

new Promise((resolve, reject) => { 
  // some async stuff here
});

function test () {
  new Prommise ((resolve, reject) => {
  });
}
```

>[!example]- Inside a function 
>![[Pasted image 20240917152524.png|center|300]] 

- `executor`: function that represents the producing code and is executed automatically and immediately.  It calls `resolve` if it was successful or `reject` if there was an error, to change the state of the promise to one state uniquely, see [[22.5 Promise constructor#There can be only a single resolve or reject|this piece of note]]. Generally is an async task

>[!important]
>Because the executor task is async, the data is not available right away, but the executor have to return something, the promise of that data, as a promise object that will have the data once the async function finish. 
>
>Think of this as a train ticket, where I get the promise will be here, but is not here right now. 

- `resolve`, `reject`: pre-defined callbacks provided automatically by JS. I only have to call them and this will change the state of the promise object. They expect only or none arguments, the rest will be ignored. 

### Internal promise object properties
The object return by the `new Promise` constructor has three internal properties:
- `[[PromiseState]]`: default value is `pending`, then changes to either `fulfilled` when `resolve` is called or `rejected` when `reject` is called.
- `[[PromiseResult]]`: default value is `undefined`, then holds the value of the executor when `resolve(value)` is called, or `error` when `reject(error)` is called.
- `[[PromiseFulfillReactions]]` hidden property.
- `[[PromiseRejectReactions]]` hidden property.
- `[[PromiseIsHandled]]`: default value is `false`. 
- Though is not a property, when a promise is either resolve or reject, its last state is called settled.
>[!blank-container|float-left]
>```js
>let promise = new Promise(function(resolve, reject) {
>  resolve("done");
>});
>console.log(promise);
>```

![[Pasted image 20240920083821.png]]

>[!attention]
>`state` and `result` are internal properties, not directly accessible. Only the `.then`, `.catch`, `.finally` methods can access them.

This means the executor moves from the pending state, to either resolve or reject, and finally to settled.

![[Pasted image 20240917101207.png|center|450]]
## How to resolve or reject a promise object
To resolve a promise the `executor` should only call one either `resolve` or `reject`. All future calls for any other state are ignored. There can be only a single resolve or reject.

```js
let promise = new Promise(function(resolve, reject) {
  resolve("done");

  reject(new Error("…")); // ignored
  setTimeout(() => resolve("…")); // ignored
});
```

>[!blank-container|float-left]
>![[Pasted image 20240918084028.png|200]]

Once the promise is resolve, the `[[PromiseState]]` updates to either reject or resolve, and `[[PromiseResult]]` updates to the value return by the resolve or reject call. 


When I want to decide I can use an if statement:

```js
// Creating a Promise (the "singer")
let promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    let success = Math.random() > 0.5;
    if (success) {
      resolve("Performance successful!");  // The "singer" completes successfully
    } else {
      reject(new Error("Performance failed!")); // The "singer" encounters an error
    }
  }, 1000);
});
```

Though the promise constructor can have a sync task, the real benefit come when an async task is performed.

![[Pasted image 20240918091838.png|center|550]]

### Use Error for reject promises
Both `reject` and `resolve` can take any value type as arguments, however, for `reject` use the `Error` objects or errors that inherit from `Error` (like in the above example). 

## Basic example
### Fulfilled promise
```js
let promise = new Promise(function(resolve, reject) {
  // the function is executed automatically when the promise is constructed

  // after 1 second signal that the job is done with the result "done"
  setTimeout(() => resolve("done"), 1000);
});
```

- The executor is called automatically and immediately.
- After one second of processing the executor calls `resolve("done")` to produce the result. 

![[Pasted image 20240917100612.png|center|450]]
### Rejecting promise
```js
let promise = new Promise(function(resolve, reject) {
  // after 1 second signal that the job is finished with an error
  setTimeout(() => reject(new Error("Whoops!")), 1000);
});
```

When the `executor` call `reject()` it changes the state of the promise object to `reject`.

![[Pasted image 20240917100823.png|center|450]]

