---
note_type: note
tags:
  - web_development
  - javascript
  - promises
mn: "[[12.5 Javascript]]"
kt: theorical
checked: false
---
[[12.5 Javascript|JavaScript]]

`finally()` code will **always** run when the promise is settled: be it resolve or reject (Think of it as a party finisher). It has no arguments as I don't know if the promise is successful or not. Finally is used to perform some cleanup, for example to stop loading indicator close connections, etc. 

Finally shouldn't return anything, if it does, the return value is ignored. The only exception to this rule is when a finally handler throws an error. Then this error goes to the next handler, instead of any previous outcome.

```js
new Promise((resolve, reject) => {
  setTimeout(() => resolve("value"), 2000);
})
  .finally(() => alert("Promise ready")) // triggers first
  .then(result => alert(result)); // <-- .then shows "value"
  .catch(err => alert(err));  // <-- .catch shows the error
```

This is a general and a complete example

```js
let p = new Promise(function(resolve, reject) {
	
	// Do an async task async task and then...

	if(/* good condition */) {
		resolve('Success!');
	}
	else {
		reject('Failure!');
	}
});

p.then(function(result) { 
	/* do something with the result */
}).catch(function() {
	/* error :( */
}).finally(function() {
   /* executes regardless or success for failure */ 
});
```